apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-manager-marvel
  labels:
    name: hero-manager-marvel
spec:
  selector:
    matchLabels:
      name: hero-manager-marvel
  replicas: 1
  template:
    metadata:
      labels:
        name: hero-manager-marvel
    spec:
      containers:
        - name: hero-manager-marvel
          image: docker.io/library/hero_manager_marvel_image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          resources: { }
          env:
            - name: MARVEL_URL
              value: https://gateway.marvel.com
            - name: MARVEL_PUBLIC_KEY
              value: 18783146f280ae0f256430efa0b5fc0f
            - name: MARVEL_PRIVATE_KEY
              value: 222fe552d91c0ced92798c32fc15c1a4b8006ff5
